const SampleSearches = [
    "How has music evolved over time? 🎹",
    "What happened before the Big Bang? 💥",
    "Famous explorers across the ages 🌎",
    "How will artificial intelligence impact society? 🤖",
    "What is the meaning of life? 🤔",
    "How to make rockets go brrrrr",
    "🖌️🎨🧑‍🎨",
    "💃🕺🎶",
    "🤖🦾🦿",
    "How can we solve climate change?",
    "Science and technology in ancient civilizations",
    "How can we become a multiplanetary species?",
    "How do we get to Mars?",
    "How has war changed over time?",
    "How do internal combustion engines work?",
    "What makes water wet",
    "What does it mean to be human",
    "How to get through tough times",
    "Basics of weight lifting",
    "How to live a meaningful life?",
    "Synthetic biology",
    "CS 3130",
    "ENWR 1510",
    "Interplay between science and religion",
    "Why does capitalism work?",
    "DS 3005",
    "RUTR 3360",
    "RELI 5094",
    "ISSS 3888",
    "What are the underlying principles of democracy",
    "Literature from across the world",
    "ASTR 3450",
    "CS 4710",
    "PHIL 1750",
    "How has education changed over time?",
    "The history of science",
    "Art of the renaissance era"
  ];
  
  export default SampleSearches;